services:

  db:
    image: postgres:13
    container_name: postgres_etl
    environment:
      POSTGRES_USER: mihavana
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: supermarket_dw
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

